# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives

# 主题
theme: minimal-mistakes-jekyll
# 皮肤"air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "default"
# 语言
locale: "zh-CN"
# 标题
title: "博客"
# # 二级标题
# subtitle: "Version 1.0"
# 用于指定站点作者
name: "che2n3jigw"
# 网站描述
description: "网站描述."
# 网站网址
url: "https://che2n3jigw.github.io"
teaser: /assets/images/default_posts_cover.jpg
# 网站刊头标题
masthead_title: "欢迎光临"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      # 样式
      layout: single
      # 显示作者信息
      author_profile: true
      related: true
      # 发布日期
      show_date: true
      # # 阅读时间
      # read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
# 代码块复制按钮
enable_copy_code_button: true
# 网站搜索
search: true

# 我的信息
author:
  name     : "陈靖文"
  avatar   : "/assets/images/avatar.jpg"
  bio      : "Android 应用开发者."
  location : "广东, 中国"
  links:
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/Che2n3JigW"

# 页脚
footer:
  since: "2025"
  links:
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/Che2n3JigW"


# 文章输出路径
permalink: /:categories/:title/

# 存档设置,该主题支持分类（类别和标签）页面。
# 使用jekyll-archives管理类别和标签
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# 压缩html
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

# 启用导航
breadcrumbs: true


# 读取文件
include:
  - _pages

# SEO
google_site_verification : PEc6jgEeO8UQEHjdBpSFIspRc5XjSUpEoSDuaj8SBvY